{
 "title": "KPM KPIs",
 "time": { "from": "now-30s", "to": "now" },
 "panels": [
  {
   "title": "UE Info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slice_id", "legendFormat": "Slice ID" },
    { "expr": "ran_ue_id", "legendFormat": "RAN UE ID" },
    { "expr": "amf_ue_ngap_id", "legendFormat": "AMF UE ID" }
   ]
  },
  {
   "title": "Slice ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "slice_id", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "DL Throughput (Kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ue_thp_dl", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "UL Throughput (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ue_thp_ul", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "DL PRB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "prb_tot_dl", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "UL PRB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "prb_tot_ul", "legendFormat": "{{rnti}}" }
   ]
  }
 ]
}