{
 "title": "PDCP Layer KPIs",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "aggregated bytes of tx packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pdcp_txpdu_pkts", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "Aggregated number of tx packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pdcp_txpdu_bytes", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "Aggregated number of rx packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "pdcp_rxpdu_pkts", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "Aggregated bytes of rx packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "pdcp_rxpdu_bytes", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "Out of order packet count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "pdcp_rxpdu_oo_pkts", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "aggregated amount of out-of-order rx bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "pdcp_rxpdu_oo_bytes", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "aggregated number of dropped or discarded rx packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "pdcp_rxpdu_dd_pkts", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "aggregated number of dropped or discarded rx bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "pdcp_rxpdu_dd_bytes", "legendFormat": "{{rnti}}" }
   ]
  },
  {
   "title": "Mode",
   "type": "timeseries",
   "description": "0: PDCP AM, 1: PDCP UM, 2: PDCP TM",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "pdcp_mode", "legendFormat": "{{rnti}}" }
   ]
  }
 ]
}